version: '3'

services:
  fhir:
    depends_on:
      - mongo
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: mongo
      DB_PORT: 27017
      DB_NAME: deqm-test-server
    ports:
      - '3000:3000'
    volumes:
      - ./src:/usr/src/app/src
    command: npm start
    stdin_open: true
    tty: true

  mongo:
    image: mongo:4.4.4
    ports:
      - '27017'
    volumes:
      - mongo_data:/data/db
      
  keycloak:
    environment:
      DB_VENDOR: h2
      KEYCLOAK_USER: user
      KEYCLOAK_PASSWORD: password
    image: jboss/keycloak:${KEYCLOAK_VERSION}
    ports:
      - "28080:8080"
    restart: unless-stopped

volumes:
  mongo_data:
