version: '3'

services:
  fhir:
    depends_on:
      - mongo
      - redis
      - validator
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SERVER_HOST: localhost
      SERVER_PORT: 3000
      DB_HOST: mongo
      DB_PORT: 27017
      DB_NAME: deqm-test-server
      IMPORT_WORKERS: 2
      NDJSON_WORKERS: 2
      REDIS_HOST: redis
      REDIS_PORT: 6379
      VALIDATE: "false"
      VALIDATOR_HOST: validator
      VALIDATOR_PORT: 4567
    ports:
      - '3000:3000'
    volumes:
      - ./src:/usr/src/app/src
    command: npm start
    stdin_open: true
    tty: true

  mongo:
    image: mongo:4.4.4
    ports:
      - '27017'
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis
    ports:
      - '6379:6379'

  validator:
    image: infernocommunity/fhir-validator-service
    ports:
      - '4567:4567'

  # TODO: Revisit keycloak setup when using an OAuth-enabled test server
  # keycloak:
  #   environment:
  #     DB_VENDOR: h2
  #     KEYCLOAK_USER: user
  #     KEYCLOAK_PASSWORD: password
  #   image: jboss/keycloak:${KEYCLOAK_VERSION}
  #   ports:
  #     - '28080:8080'
  #   restart: unless-stopped

volumes:
  mongo_data:
